language: c

addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake

sudo: false

env:
  - BUILD_TYPE=tiny
  - BUILD_TYPE=regular-asm

os:
  #  - linux
  #  - osx

before_install:
  - git submodule update --init --recursive
  - git submodule update --recursive

script:
  - WITHOUT_AMALG=1 make ${BUILD_TYPE}
  - make test

notifications:
  email: true
  irc: "irc.freenode.org#luvit"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/90c4eb53cc2fa148a058
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

jobs:
  include:
    #  - stage: deploy
    #    if: tag IS present
    #    os: linux
    #    env: []
    #    script:
    #      # fetch tags so that git describe works
    #      - git fetch --unshallow
    #      - make linux-build
    #    services:
    #      - docker
    #    deploy:
    #      provider: releases
    #      api_key: $GITHUB_OAUTH_TOKEN
    #      file:
    #        - "luvi-regular-Linux_x86_64"
    #        - "luvi-tiny-Linux_x86_64"
    #        - "luvi-regular-Linux_i686"
    #        - "luvi-tiny-Linux_i686"
    #      overwrite: true
    #      skip_cleanup: true
    #      on:
    #        tags: true
    - stage: deploy
      if: tag IS present
      os: osx
      env: []
      script:
        # fetch tags so that git describe works
        - git fetch --unshallow
        - make travis-publish
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "luvi-regular-Darwin_x86_64"
          - "luvi-tiny-Darwin_x86_64"
        overwrite: true
        skip_cleanup: true
        on:
          tags: true
